parameters:
  displayName: 'Rename Telerik license file'
  currentFileName: 'telerik-license.txt'
  newFileName: 'telerik-license-corrupted.txt'

steps:
- powershell: |
    $appData = [Environment]::GetFolderPath('ApplicationData')
    $folder = Join-Path $appData 'Telerik'
    $source = Join-Path $folder ${{ parameters.currentFileName }}
    $destination = Join-Path $folder ${{ parameters.newFileName }}

    if (Test-Path $source) {
        Rename-Item -Path $source -NewName (Split-Path $destination -Leaf)
        Write-Output "File renamed successfully: $source → $destination"
    } else {
        Write-Output "Source file does not exist: $source"
    }
  displayName: ${{ parameters.displayName }}
